name: GitFlow Release
on:
    pull_request:
        branches:
            - 'develop'
        types:
            - closed

jobs:
    print_info:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo HEAD_REF: ${{ github.head_ref }}
                echo HEAD starts with 'release/': ${{ startsWith(github.head_ref, 'release/') }}
                echo Merged: ${{ github.event.pull_request.merged }}
                echo should run: ${{ startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged }}
    if_merged:
        if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - name: Is release PR check
              run: |
                echo A 'release' PR has been merged: ${{ github.head_ref }}
            - name: Checkout master
              uses: actions/checkout@v3
              with:
                ref: master

            - run: |
                version=$(basename github.head_ref)
                echo $version
                git fetch origin
                git merge --squash ${{ github.head_ref }}
                git tag $version
                git push
                git push --tags