name: GitFlow Release
on:
    pull_request:
        branches:
            - 'develop'
        types:
            - closed

jobs:
    print_info:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo HEAD_REF: ${{ github.head_ref }}
                echo HEAD starts with 'release/': ${{ startsWith(github.head_ref, 'release/') }}
                echo Merged: ${{ github.event.pull_request.merged }}
                echo should run: ${{ startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged }}
                echo REPOSITORY URL: ${{ github.repositoryUrl }}
    if_merged:
        if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - name: Is release PR check
              run: |
                echo A 'release' PR has been merged: ${{ github.head_ref }}

            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: master

            - name: Merge release -> master
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: development
                target_branch: master
                github_token: ${{ secrets.GITHUB_TOKEN }}