name: GitFlow Release
on:
    pull_request:
        branches:
            - 'develop'
        types:
            - closed

jobs:
    if_merged:
        if: startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo A 'release' PR has been merged: ${{ github.head_ref }}